api_token: YOUR-API-TOKEN-HERE
sleep: 2 # Sleep time (secs) between API calls
n_cores: 4 # Number of cored for some multi-ptocessing operations
only_current: false # Only fetch data for current year
leagues : [
            [England, Premier League],
            [England, Championship],
            [England, EFL Trophy],
            [England, FA Cup],
            [England, FA Trophy],
            [England, League Cup],
            [England, League One],
            [England, League Two],
            [England, National League],
            [England, Community Shield],
            [France, Ligue 1],
            [France, Ligue 2],
            [France, Coupe de France],
            [France, Coupe de la Ligue],
            [France, National],
            [France, National 2 - Group A],
            [France, National 2 - Group B],
            [France, National 2 - Group C],
            [France, National 2 - Group D],
            [France, Trophée des Champions],
            [Germany, Bundesliga 1],
            [Germany, Bundesliga 2],
            [Germany, DFB Pokal],
            [Germany, Liga 3],
            [Germany, Super Cup],
            [Germany, U19 Bundesliga],
            [Italy, Serie A],
            [Italy, Super Cup],
            [Italy, Coppa Italia],
            [Italy, Serie B],
            [Italy, Serie C],
            [Portugal, Primeira Liga],
            [Portugal, Liga de Honra],
            [Portugal, Super Cup],
            [Portugal, Taça de Portugal],
            [Spain, Primera Division],
            [Spain, Segunda Division],
            [Spain, Super Cup],
            [Spain, Copa del Rey],
            [Spain, Segunda B - Group 1],
            [Spain, Segunda B - Group 2],
            [Spain, Segunda B - Group 3],
            [Spain, Segunda B - Group 4]
]